module.exports = [
  'Burger Bistro',
  "The Smokin' Patty",
  'The Burger Joint',
  'Beefcakes Burgers',
  'The Burger House',
  'The Crispy Bun',
  'Burger Smokehouse',
  'The Burger Grille',
  'Backyard Burgers',
  'Beefcakes Burgers',
  'Dungeon Burgers',
  'Burger 54',
  'Burger King',
  'Mc Donalds',
  'Carne',
  "Wendy's",
  'Kansas',
  'Tucson',
  'Arredondo',
  'Perez H',
  'The Burger Hub',
  'The Burgery',
  'Mi Barrio',
  'Heinseburger',
  'Burgers-a-Billion',
  'We Love Beef',
  'Burger Bistro',
  'Hot Cross Buns',
  'Deniro',
  'The Burger Company',
  'Burger House',
  'Dean & Dennys',
  'Fat Broder',
  'Big Pons',
  'Tierra de Nadie',
  'La Birra Bar',
  'Pony Line',
  'Burgertify',
  'Voraz',
  'Paris Burger',
  'Open Door Burger',
  'La Pinta',
  'Wunderbar',
  'Olika',
  'Cova',
  'Berim',
  'Aloha Burgers',
  'Bruce Grill Station',
  'Saint Burger',
  'Mostaza',
];
